on:
  push:
  schedule:
    - cron: '0 18 * * *'
name: Update
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Update data
      id: update
      run: make all
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        # Versioning is current date
        format: "YYYY.M.D"
    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: Update Electron Fingerprints
        commit_author: actions-user <65916846+actions-user@users.noreply.github.com>
        file_pattern: hashes/*.json lookup/*.json
        status_options: '--untracked-files=no'
    - name: NPM Version Bump
      run: |
        npm version "v${{ steps.current-time.outputs.formattedTime }}"
        git push origin --tags
      if: ${{ steps.commit.output.changes_detected}}
    # TODO: NPM Publish
