on: 
  push:
  schedule:
    - cron: '0 18 * * *'
name: Update
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        # Versioning is current date
        format: "YYYY.M.D"
    - name: Update data
      run: make all
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Electron Fingerprints
        commit_author: actions-user <65916846+actions-user@users.noreply.github.com>
        tagging_message: "v${{ steps.current-time.outputs.formattedTime }}"
        file_pattern: hashes/*.json lookup/*.json
        status_options: '--untracked-files=no'